---

- name: Execute OSX iTerm2 install
  import_tasks: osx-configure-iterm.yaml
  when: ansible_os_family == 'Darwin'

- name: Execute OSX configuration
  import_tasks: osx-configure-system.yaml
  when: ansible_os_family == 'Darwin'

- name: Execute OSX Dock configuration
  import_tasks: osx-configure-dock.yaml
  when: ansible_os_family == 'Darwin'