---

- name: Run OSX configuration command (#1/2)
  shell: "{{ item }}"
  loop: "{{ sys_conf_commands }}"

- name: Run OSX configuration command (#2/2 as root)
  shell: "{{ item }}"
  loop: "{{ sys_conf_commands_root }}"
  become: yes

- name: Copy SMB config /etc/nsmb.conf
  copy:
    src: "{{ role_path }}/files/nsmb.conf"
    dest: "/etc/nsmb.conf"
    force: no
  become: yes

- name: Missing manual steps [DO THIS MANUALLY]
  debug:
    msg:
      - "System Preferences"
      - " -> Dock & Menu Bar"
      - "    [ ] Show recent applications in Docks"
      - "   -> Battery"
      - "   [x] Show percentage"
      - " -> Apple ID"
      - "    Sign In (If not done)"
      - " -> General"
      - "    [x] Ask to keep changes when closing documents"
      - "    Resent items: None"
      - "    [ ] Allow Handoff between this Mac and your iCloud devices"
      - " -> Desktop & Screen Saver"
      - "   -> Desktop"
      - "     Solid Colors = Blue"
      - "   -> Screen Saver"
      - "     Start after = 5 Minute"
      - "     -> Hot Corners"
      - "       Left Top = Put Display to Sleep"
      - " -> Mission Control"
      - "    [ ] Automatically rearrange Spaces based on most recent use"
      - "    [ ] Displays have separate Spaces"
      - " -> Users & Groups"
      - "    Select your user"
      - "     -> Login Items"
      - "        Add Spectacle"
      - "        Add Tomighty"
      - "    Guest User"
      - "      [ ] Allow guests to log in to this computer"
      - " -> Security & Privacy"
      - "   -> General"
      - "      [x] Required password immediately"
      - "   -> FileVault"
      - "      Turn On"
      - "   -> Firewall"
      - "      Turn On"
      - " -> Keyboard"
      - "   -> Keyboard"
      - "      [x] Turn keyboard backlight off after 5 secs"
      - "      [x] Use F1, F2 ....  aka Press Fn key to: Show F1,F2"
      - " -> Trackpad"
      - "   -> Point & Click"
      - "      [ ] Look up & data detectors"
      - "      [x] Tap to click"
      - "   -> Scroll & Zoom"
      - "      [ ] Scroll direction: Natural"
      - " -> Displays"
      - "   -> Night Shift"
      - "      Schedule: Sunset to Sunrise"
      - " -> Date & Time"
      - "   -> Clock"
      - "      [x] Show date and time in menu bar"
      - " -> Time Machine"
      - "      [x] Back Up Automatically"
      - "      [x] Show Time Machine in menu bar"
      - "Applications"
      - " -> Finder"
      - "   -> Preference"
      - "      -> General"
      - "        [ ] for all: Show these items on the desktop"
      - "        New Finder windows show: /Users/<home>"
      - "      -> Sidebar"
      - "        [ ] iCloud Drive"
      - "        [ ] Tags"
      - "        Select rest as liked"
      - "   -> Go -> Connect to Server.."
      - "      afp://..."
      - "   -> Favourites (left bar)"
      - "      Desktop"
      - "      <home>"
      - "      Dropbox"
      - "      Google Drive"
      - "      AirDrop"
      - "      Applications"
      - " -> Messages"
      - "   -> Preferences"
      - "     -> Tab iMessage"
      - "       -> In left tab select account to disable"
      - "         -> Click Sign Out"
      - " -> FaceTime"
      - "   -> Preferences"
      - "     -> Click Sign Out"
      - " -> Dropbox"
      - " -> Google Backup & Sync"
      - "    Setup, sync add to startup"
      - " -> Banking 4X"
      - "    Enter Licence"

- name: Remove the 'last login' message from the terminal
  file:
    path: "~/.hushlogin"
    state: touch