---

- name: Check if homebrew is Installed
  stat:
    path: "/usr/local/bin/brew"
  register: "homebrew_check"

- name: Install homebrew (using CURL)
  shell: '/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"'
  when: not homebrew_check.stat.exists

- name: homebrew update itself and packages
  homebrew:
    update_homebrew: yes
    upgrade_all: yes
  when: homebrew_check.stat.exists

- name: hombrew list tap's
  command: brew tap
  register: brew_tap_list

- name: homebrew add tap's
  homebrew_tap: "tap={{ item }} state=present"
  loop: "{{ brew_taps }}"
  when: "item.name | default(item) not in brew_tap_list.stdout"

- name: hombrew list packages
  command: brew list --formula
  register: brew_list

- name: homebrew install packages
  homebrew:
    name: "{{ item.name | default(item) }}"
    install_options: "{{ item.install_options | default(omit) }}"
    state: present
  loop: "{{ brew_packages }}"
  when: "item.name | default(item) not in brew_list.stdout"

- name: hombrew cask list packages
  command: brew list --cask
  register: brew_cask_list

- name: homebrew cask install packages
  homebrew_cask:
    name: "{{ item.name | default(item) }}"
    install_options: "{{ item.install_options | default(omit) }}"
    state: present
  loop: "{{ brew_cask_packages }}"
  when: "item.name | default(item) not in brew_cask_list.stdout"