---

dockutil_remove:
  - "TV"
  - "Podcasts"
  - "Music"
  - "Siri"
  - "Launchpad"
  - "Mail"
  - "Contacts"
  - "Calendar"
  - "Notes"
  - "Reminders"
  - "Maps"
  - "Photos"
  - "Messages"
  - "FaceTime"
  - "iTunes"
  - "iBooks"
  - "Downloads"
  - "Terminal"
  - "Safari"
  - "App Store"

dockutil_persist:
  # List all existing: dockutil --list
  - { name: "Launchpad",                  path: "/System/Applications/Launchpad.app",                   pos: 1 }
  - { name: "Activity Monitor",           path: "/System/Applications/Utilities/Activity Monitor.app",  pos: 2 }
  - { name: "System Preferences",         path: "/Applications/System Preferences.app",                 pos: 3 }
  - { name: "iTerm",                      path: "/Applications/iTerm.app",                              pos: 4 }
  - { name: "MacPass",                    path: "/Applications/MacPass.app",                            pos: 5 }
  - { name: "Spotify",                    path: "/Applications/Spotify.app",                            pos: 6 }
  - { name: "Thunderbird",                path: "/Applications/Thunderbird.app",                        pos: 7 }
  - { name: "Google Chrome",              path: "/Applications/Google Chrome.app",                      pos: 8 }
  - { name: "Firefox Developer Edition",  path: "/Applications/Firefox Developer Edition.app",          pos: 9 }
  - { name: "Joplin",                     path: "/Applications/Joplin.app",                             pos: 10 }
  - { name: "Sublime Text",               path: "/Applications/Sublime Text.app",                       pos: 11 }
  - { name: "Visual Studio Code",         path: "/Applications/Visual Studio Code.app",                 pos: 12 }
  - { name: "PhpStorm",                   path: "/Applications/PhpStorm.app",                           pos: 13 }
  - { name: "PyCharm CE",                 path: "/Applications/PyCharm CE.app",                         pos: 14 }
  - { name: "Slack",                      path: "/Applications/Slack.app",                              pos: 15 }
  - { name: "Clockify Desktop",           path: "/Applications/Clockify Desktop.app",                   pos: 16 }

# See https://github.com/herrbischoff/awesome-osx-command-line
sys_conf_commands:
  - "defaults write -g QLPanelAnimationDuration -float 0" # Disable animations when opening a Quick Look window
  - "defaults write -g NSWindowResizeTime -float 0.001" # Disable screen resizing animation of OS X
  - "defaults write -g NSAutomaticWindowAnimationsEnabled -bool false" # Disable animations when opening and closing windows
  - "defaults write -g NSToolbarFullScreenAnimationDuration -float 0" # Showing a toolbar or menu bar in full screen
  - "defaults write -g NSScrollViewRubberbanding -bool false" # Disable rubberband scrolling
  - "defaults write -g NSBrowserColumnAnimationSpeedMultiplier -float 0" # Disable scrolling column views
  - "defaults write -g ApplePressAndHoldEnabled -bool false" # Disable accent popup https://apple.stackexchange.com/questions/105098/how-do-i-re-enable-the-press-and-hold-character-picker-on-os-x-lion
  - "defaults write -g KeyRepeat -int 1" # The keyboard react faster to keystrokes https://apple.stackexchange.com/questions/10467/how-to-increase-keyboard-key-repeat-rate-on-os-x
  - "defaults write -g InitialKeyRepeat -int 10" # -"-
  - "defaults write -g AppleShowAllExtensions -bool true" # Display file extensions in Finder
  - "defaults write -g NSNavPanelExpandedStateForSaveMode -bool true" # Enable the expand save panel by default
  - "defaults write -g NSNavPanelExpandedStateForSaveMode2 -bool true" # -"-
  - "defaults write -g AppleShowScrollBars -string 'Always'" # Always show scrollbars ( Possible values: `WhenScrolling`, `Automatic` and `Always`)
  - "defaults write -g PMPrintingExpandedStateForPrint -bool true" # Expand print panel by default
  - "defaults write -g PMPrintingExpandedStateForPrint2 -bool true" # -"-
  - "defaults write -g NSAutomaticCapitalizationEnabled -bool false" # Disable auto capitalize
  - "defaults write -g NSAutomaticPeriodSubstitutionEnabled -bool false" # Disable auto period insert
  - "defaults write -g AppleMiniaturizeOnDoubleClick -bool false" # Double-click a window's title bar to minimize
  - "defaults write -g com.apple.swipescrolldirection -bool false" # Set scroll direction
  - "defaults write com.apple.finder AppleShowAllFiles YES" # Allowing Finder to show hidden files
  - "defaults write com.apple.finder DisableAllAnimations -bool true" # Disable animation when opening the Info window in OS X Finder (cmd⌘ + i)
  - "defaults write com.apple.finder _FXShowPosixPathInTitle -bool true" # Display full posix path in OS X Finder title Bar
  - "defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false" # Disable the extension change warning in OS X Finder
  - "defaults write com.apple.finder FXDefaultSearchScope -string 'SCcf'" # When performing a search, search the current folder by default
  - "defaults write com.apple.finder FXPreferredViewStyle -string 'clmv'" # Use list view in all Finder windows by default (Four-letter codes for the other view modes: `icnv` Icon View, `Nlsv` List View, `clmv` Column View, `Flwv` Cover Flow View)
  - "defaults write com.apple.finder FXInfoPanesExpanded -dict General -bool true OpenWith -bool true Privileges -bool true" # Expand the following File Info panes
  - "defaults write com.apple.finder NewWindowTarget -string 'PfHm'" # New window points to home
  - "defaults write com.apple.finder ShowStatusBar -bool true" # Show status bar in finder
  - "defaults write com.apple.dock launchanim -bool false" # Disable animations when you open an application from the Dock
  - "defaults write com.apple.dock expose-animation-duration -float 0" # Make all animations faster that are used by Mission Control
  - "defaults write com.apple.dock autohide-delay -float 0" # Disable the delay when you hide the Dock
  - "defaults write com.apple.dock autohide-time-modifier -float 0" # -"-
  - "defaults write com.apple.dock tilesize -int 50" # Set size of dock menu
  - "defaults write com.apple.dock mineffect -string 'scale'" # Change minimize/maximize window effect
  - "defaults write com.apple.dock minimize-to-application -bool true" # Minimize windows into their application’s icon
  - "defaults write com.apple.dock springboard-show-duration -float 0" # Disable delay showing and hiding Launchpad
  - "defaults write com.apple.dock springboard-hide-duration -float 0" # -"-
  - "defaults write com.apple.dock springboard-page-duration -float 0" # Disable delay changing pages in Launchpad
  - "defaults write com.apple.desktopservices DSDontWriteNetworkStores true" # Prevent .DS_Store file creation over network connections
  - "defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true" # Prevent .DS_Store file creation on USB devices
  - "defaults write com.apple.screencapture disable-shadow -bool true" # Screenshots without window shadows
  - "defaults write com.apple.TextEdit RichText -int 0" # Use plain text as default format in TextEdit
  - "defaults write com.apple.Safari WebKitInitialTimedLayoutDelay 0.25" # Disable the standard delay in rendering safari a web page
  - "defaults write com.apple.screensaver askForPassword -int 1" # Require password immediately after sleep or screen saver begins
  - "defaults write com.apple.screensaver askForPasswordDelay -int 0" # -"-
sys_conf_commands_root:
  - "/System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -deactivate -stop" # Deactivate and Stop the Remote Management Service
  - "defaults write com.apple.TimeMachine DoNotOfferNewDisksForBackup -bool true" # Prevent Time Machine from Prompting to Use New Hard Drives as Backup Volume
  - "/usr/libexec/ApplicationFirewall/socketfilterfw --setglobalstate on" # Enable Application Firewall
  #- "networksetup -setdnsservers 'Thunderbolt Ethernet' 9.9.9.9 1.1.1.1" # Change DNS server, to see devices run 'networksetup -listallnetworkservices' https://superuser.com/questions/86184/change-dns-server-from-terminal-or-script-on-mac-os-x
