---

- name: Check if all_secret.sh exists
  stat:
    path: "{{ role_path }}/src/bash_zsh/all_secret.sh"
  register: all_secret

- name: Copy all_secret.sh from *-example.sh
  copy:
    src:  "{{ role_path }}/src/bash_zsh/all_secret-example.sh"
    dest: "{{ role_path }}/src/bash_zsh/all_secret.sh"
  when: not all_secret.stat.exists

- name: Replace HOMEBREW_GITHUB_API_TOKEN
  lineinfile:
    path: "{{ role_path }}/src/bash_zsh/all_secret.sh"
    regexp: '^#export HOMEBREW_GITHUB_API_TOKEN'
    line: "export HOMEBREW_GITHUB_API_TOKEN=\"{{ github_token }}\""
  when: not all_secret.stat.exists

- name: Check if oh-my-fish is Installed
  stat:
    path: "$HOME/.local/share/omf"
  register: "omf_check"

- debug:
      msg: "oh-my-fish already installed"
  when: omf_check.stat.exists

- name: Install oh-my-fish (using CURL) # https://theworkaround.com/2016/10/11/installing-fish-on-osx.html
  shell: 'curl -L http://get.oh-my.fish | fish'
  when: not omf_check.stat.exists

- name: Install dotfiles using bootstrap.py script
  command: "{{ role_path }}/bin/bootstrap.py"
  register: bootstrap

- name: Show result of bootstrap.py
  debug: var=bootstrap.stdout_lines
