---

- name: Install tmux package on OSX using hombrew
  import_tasks: osx-tmux-install.yaml
  when: ansible_os_family == 'Darwin'

- name: Fetch tmux version
  command: "tmux -V"
  register: bootstrap

- name: Install tmux plugin manager and config
  import_tasks: tmux-install-plugin-config.yaml
  when:  bootstrap.stdout.split(' ')[1] is version('2.8', '>=')