---

- name: Execute OSX hombrew installation for python
  import_tasks: osx-python-install.yaml
  when: ansible_os_family == 'Darwin'

- name: Copy pip config
  copy:
    src: "{{ role_path }}/files/"
    dest: "~"
    force: yes

# When issue is solved https://github.com/pyenv/pyenv/issues/1643 (2020-12-24) -> BUILD FAILED (OS X 11.1 using python-build 20180424)
# Install python via pyenv -> https://github.com/pyenv/pyenv
# Install latest with https://github.com/momo-lab/xxenv-latest

#- name: Update setuptools
#  shell: 'python3 -m pip install --upgrade setuptools'
#  environment:
 #       PIP_REQUIRE_VIRTUALENV: false

- name: Update setuptools
  shell: 'pip install --upgrade setuptools'
  environment:
        PIP_REQUIRE_VIRTUALENV: false

- name: Update pip
  shell: 'pip install --upgrade pip'
  environment:
        PIP_REQUIRE_VIRTUALENV: false

- name: Install system python packages
  pip:
    name: "{{ item }}"
    state: latest
    extra_args: --user
  loop: "{{ python_packages }}"
  environment:
        PIP_REQUIRE_VIRTUALENV: false