---

# https://docs.ansible.com/ansible/latest/user_guide/playbooks_delegation.html#local-playbooks
- name: Setup system
  hosts: localhost
  connection: local

  vars_prompt:
    - name: "ansible_sudo_pass"
      prompt: "Sudo password"
      private: yes

  roles:
    - homebrew
    - zsh_oh-my-zsh
    - dotfiles
    - git
    - vscode