
---

- name: Install sublime text package control
  get_url:
    url: "https://packagecontrol.io/Package Control.sublime-package"
  args:
    dest: ~/Library/Application Support/Sublime Text 3/Installed Packages
    mode: 0644

- name: Install sublime-text settings
  copy:
    src: "{{ role_path }}/files/"
    dest: "~/Library/Application Support/Sublime Text 3/Packages/User/"
    force: yes