---

- name: homebrew install duti package see https://github.com/moretension/duti
  homebrew:
    name: "{{ item.name | default(item) }}"
    install_options: "{{ item.install_options | default(omit) }}"
    state: present
    update_homebrew: yes
  loop:
    - duti

# See
# http://duti.org/documentation.html
# https://en.wikipedia.org/wiki/Uniform_Type_Identifier
# https://superuser.com/questions/273756/how-to-change-default-app-for-all-files-of-particular-file-type-through-terminal
# and also `man duti`

- name: Update file type association using duti
  command: "duti -s {{ item.0.bundle_id }} {{ item.1 }} all"
  with_subelements:
    - "{{ duti_associations }}"
    - utis